table OrdersDetails
	lineageTag: 3bbeea86-a9bc-43a1-8b61-9b05092997f8

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: aaefca0e-dd30-41d9-a0ec-0b20655846a1
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column RowID
		dataType: int64
		formatString: 0
		lineageTag: 8e1b94d1-64ab-4f90-beb8-332794148493
		summarizeBy: count
		sourceColumn: RowID

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 6575a4ea-a105-4f21-8642-3540e9bee8f5
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		formatString: 0
		lineageTag: 4422e92b-a205-4b55-a279-ae42e4c71208
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	partition OrdersDetails = m
		mode: import
		queryGroup: Data
		source = ```
				let    
				    SourceTable = CsvGzImporter(DataFolder & "OrdersDetails", 4),    
				    OutTable = Table.TransformColumnTypes(SourceTable,{{"OrderID", Int64.Type}, {"RowID", Int64.Type}, {"Item", type text}, {"Price", type number}}, "en-US")
				    
				in
				    OutTable
				```

	annotation PBI_ResultType = Table

