table SAOrders
	lineageTag: dc13a9fe-a4aa-40ce-a80f-b8d8f901b3c0

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 5fb3b3f4-fec2-45d0-b30a-dda9c55d110f
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column DT
		dataType: dateTime
		formatString: General Date
		lineageTag: bb0023ab-5002-48a9-bb8f-9230669b28f3
		summarizeBy: none
		sourceColumn: DT

		variation Variation
			isDefault
			relationship: b427f877-8a09-468a-ab9c-a33df399a16f
			defaultHierarchy: LocalDateTable_b0d6d310-71c0-4449-9850-5215c4700ec1.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: cfea88fc-4f8c-47a6-9cab-3755f5c4b92c
		summarizeBy: count
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	partition SAOrders = m
		mode: import
		queryGroup: Data
		source = ```
				let
				    GZFiles     = RetrieveFromSA(SAName, SAContainer, "orderscsvgz/"),
				    CSVData     = ExpandCsvGz(GZFiles, 3),
				    FinalOutput = Table.TransformColumnTypes(CSVData, {{"OrderID", Int64.Type}, 
				                                                       {"DT", type datetime}, 
				                                                       {"CustomerID", Int64.Type}})   
				in
				    FinalOutput
				```

	annotation PBI_ResultType = Table

