table SAOrdersDetails
	lineageTag: a417210d-a723-43c1-b474-96e653e6c133

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: 161513ab-67d5-42f5-8757-a38f03283902
		summarizeBy: none
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column RowID
		dataType: int64
		formatString: 0
		lineageTag: d08726d7-d081-47f8-9f40-35480fd59ff2
		summarizeBy: count
		sourceColumn: RowID

		annotation SummarizationSetBy = Automatic

	column Item
		dataType: string
		lineageTag: 1bf8eabf-2c09-4f9a-8590-7899807c5b7c
		summarizeBy: none
		sourceColumn: Item

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: double
		lineageTag: 94019229-5f90-4ebf-9dc1-ca0ce86354b5
		summarizeBy: sum
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition SAOrdersDetails = m
		mode: import
		queryGroup: Data
		source = ```
				let
				    GZFiles     = RetrieveFromSA(SAName, SAContainer, "ordersdetailscsvgz/"),
				    CSVData     = ExpandCsvGz(GZFiles, 4),
				    FinalOutput = Table.TransformColumnTypes(CSVData,{{"OrderID", Int64.Type}, 
				                                                      {"RowID", Int64.Type}, 
				                                                      {"Item", type text}, 
				                                                      {"Price", type number}}, 
				                                             "en-US")    
				in
				    FinalOutput
				```

	annotation PBI_ResultType = Table

