{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.927.0 (24.02)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DataFolder\",\"CsvGzImporter\",\"Orders\",\"OrdersDetails\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "DataFolder",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Text"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "expression": "\"X:\\work_fabry\\src\\GitHub\\powerbi-multi-csv-gz.git\\Data\\\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "33f827b9-34f7-4807-aa4a-02105555910a",
        "queryGroup": "Data"
      },
      {
        "name": "CsvGzImporter",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    MyFunct = (DataFolder as text, NumOfFields as number) =>  let   ",
          "    ",
          "        Source = Folder.Files(DataFolder & \"\"),",
          "",
          "        gzOnlyFiles =  Table.RenameColumns(",
          "                        Table.SelectColumns(",
          "                            Table.SelectRows(",
          "                                Source,",
          "                                each [Extension] = \".gz\"),",
          "                            {\"Name\", \"Content\"}),",
          "                        {\"Name\", \"GZFileName\"}),",
          "",
          "        withCsvBody = Table.AddColumn(gzOnlyFiles, \"csvbody\", each Binary.Decompress([Content], Compression.GZip)  ),",
          "        withCsvTable = Table.AddColumn(withCsvBody , \"csvtable\", each Csv.Document([csvbody],[Delimiter=\",\", Columns=NumOfFields, Encoding=1252, QuoteStyle=QuoteStyle.None])   ),",
          "        withCsvTableHeaders = Table.AddColumn(withCsvTable, \"csvtableH\", each Table.PromoteHeaders([csvtable] , [PromoteAllScalars=true] ) ),",
          "        firstTableColumns = Table.ColumnNames(Table.First(withCsvTableHeaders)[csvtableH]),",
          "        expandTable = Table.ExpandTableColumn(withCsvTableHeaders, \"csvtableH\",  firstTableColumns),",
          "        finalTable = Table.RemoveColumns(expandTable, {\"GZFileName\", \"Content\", \"csvbody\", \"csvtable\"})  ",
          "",
          "    in",
          "        finalTable",
          "",
          "in",
          "    MyFunct"
        ],
        "kind": "m",
        "lineageTag": "efa5fc63-890e-4eaa-8fb4-5fa6f18656f0",
        "queryGroup": "Data"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Data"
      }
    ],
    "relationships": [
      {
        "name": "2f053237-7ed6-41b4-8a5b-588976ea38d0",
        "fromColumn": "DT",
        "fromTable": "Orders",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3fd8f3fd-91b0-4776-80af-bd8c78e12aff"
      },
      {
        "name": "b19c0edd-51eb-4db6-9a4e-60bdfe6eebab",
        "fromColumn": "OrderID",
        "fromTable": "OrdersDetails",
        "toColumn": "OrderID",
        "toTable": "Orders"
      }
    ],
    "sourceQueryCulture": "it-IT",
    "tables": [
      {
        "name": "DateTableTemplate_b63610e3-dbc9-479e-976f-f76358f54d3a",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "061fc33f-679c-4579-b525-0e7da7a5ce3d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fe32d56d-70c8-46e3-9aa2-0ca6b3e3f9b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "1f33152b-2dd2-4575-b7a8-32476e648cca",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "43df4cec-0ca0-478a-b568-2037ae3276ad",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "18039d02-8c24-4fba-8563-1f1318baa994",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "924c1c5c-914c-4920-9058-657d15c8bcae",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "910004df-bc9b-4eed-b05e-1294e73eca2d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2706f38a-4022-4905-8a30-13cbf9c351d1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "addfb423-3ff4-43a1-9439-d93de268ad60",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c7a3fb26-1d45-49cb-8262-679f9b2af862",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e5f274fe-2329-4f89-a3af-b96fecaee3de",
                "ordinal": 3
              }
            ],
            "lineageTag": "cd13c119-29c5-4adc-a58a-e17fcf3b3996"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "0a841cd9-35b0-4338-8d7d-cbbf834d8fd0",
        "partitions": [
          {
            "name": "DateTableTemplate_b63610e3-dbc9-479e-976f-f76358f54d3a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Orders",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee659294-6edf-446f-a14f-ffd01c341398",
            "sourceColumn": "OrderID",
            "summarizeBy": "none"
          },
          {
            "name": "DT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "42946a95-cb9a-4366-a2ff-f5645e5dba9f",
            "sourceColumn": "DT",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_3fd8f3fd-91b0-4776-80af-bd8c78e12aff"
                },
                "isDefault": true,
                "relationship": "2f053237-7ed6-41b4-8a5b-588976ea38d0"
              }
            ]
          },
          {
            "name": "CustomerID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9246d389-849c-4546-8ffc-cd5f8a2ab172",
            "sourceColumn": "CustomerID",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "84c68e70-fa13-4892-b0bb-00c70b9a4280",
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "queryGroup": "Data",
            "source": {
              "expression": [
                "let    ",
                "    SourceTable = CsvGzImporter(DataFolder & \"Orders\", 3),",
                "    OutTable = Table.TransformColumnTypes(SourceTable,{{\"OrderID\", Int64.Type}, {\"DT\", type datetime}, {\"CustomerID\", Int64.Type}})",
                "in",
                "    OutTable"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3fd8f3fd-91b0-4776-80af-bd8c78e12aff",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "be0691f7-f4aa-45f5-8d3c-0ad193742718",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9890e9a4-2554-469d-8978-eacdcf358c97",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0e6bfdba-db0e-48aa-bb6d-9ac8ab90ce35",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4229e681-d0eb-4181-ac32-4c69799ba4a2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "8d54fdf5-388d-44b0-b403-a390441ffca5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7bb2c327-6eef-49ff-b2c8-31ea97a9d568",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "44a93210-6266-4ba6-af1f-47b302b2371c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "74f8d86d-a072-41e1-a141-394e2ccbea26",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b5ade716-3196-4466-9652-bb0e03a14a92",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "1494181c-31a6-4ed6-8948-2b640e2e30a6",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "fa497f4d-4545-4ff9-9bab-bc5e83b08746",
                "ordinal": 3
              }
            ],
            "lineageTag": "7e18f00d-ce44-4609-b169-4aa9f9bdb5e9"
          }
        ],
        "isHidden": true,
        "lineageTag": "e4d2804e-236e-4254-853f-c006ef44c7c1",
        "partitions": [
          {
            "name": "LocalDateTable_3fd8f3fd-91b0-4776-80af-bd8c78e12aff",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Orders'[DT])), 1, 1), Date(Year(MAX('Orders'[DT])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "OrdersDetails",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "OrderID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aaefca0e-dd30-41d9-a0ec-0b20655846a1",
            "sourceColumn": "OrderID",
            "summarizeBy": "none"
          },
          {
            "name": "RowID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e1b94d1-64ab-4f90-beb8-332794148493",
            "sourceColumn": "RowID",
            "summarizeBy": "count"
          },
          {
            "name": "Item",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6575a4ea-a105-4f21-8642-3540e9bee8f5",
            "sourceColumn": "Item",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4422e92b-a205-4b55-a279-ae42e4c71208",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "3bbeea86-a9bc-43a1-8b61-9b05092997f8",
        "partitions": [
          {
            "name": "OrdersDetails",
            "mode": "import",
            "queryGroup": "Data",
            "source": {
              "expression": [
                "let    ",
                "    SourceTable = CsvGzImporter(DataFolder & \"OrdersDetails\", 4),    ",
                "    OutTable = Table.TransformColumnTypes(SourceTable,{{\"OrderID\", Int64.Type}, {\"RowID\", Int64.Type}, {\"Item\", type text}, {\"Price\", type number}}, \"en-US\")",
                "    ",
                "in",
                "    OutTable"
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}